# Generated by Django 3.0.2 on 2020-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('PW', models.CharField(max_length=30)),
            ],
        ),
    ]
