# Generated by Django 3.0.2 on 2020-07-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='mylab.Directory'),
        ),
    ]
